function [] = add_SEEG_NPD_paths()
if strcmp(getenv('COMPUTERNAME'),'SFLAP-2')
    addpath(genpath('C:\Users\Tim\Documents\Work\GIT\SEEG_NPD'))
elseif strcmp(getenv('COMPUTERNAME'),'FREE')
    addpath(genpath('C:\Users\twest\Documents\Work\Github\SEEG_NPD\Preprocessing'))
    addpath('C:\Users\twest\Documents\Work\MATLAB ADDONS\gramm-master\@gramm')   
    addpath('C:\Users\twest\Documents\Work\MATLAB ADDONS\SplitVec')
    addpath('C:\Users\twest\Documents\Work\MATLAB ADDONS\aboxplot')
    addpath(genpath('C:\Users\twest\Documents\Work\MATLAB ADDONS\boundedline-pkg'))
    addpath(genpath('C:\Users\twest\Documents\Work\MATLAB ADDONS\DylanMuir-ParforProgMon-9a1c257'))
    addpath('C:\Users\twest\Documents\Work\MATLAB ADDONS\linspecer')
    addpath('C:\Users\twest\Documents\Work\MATLAB ADDONS\TWtools')
    addpath('C:\Users\twest\Documents\Work\MATLAB ADDONS\sigstar-master')
    addpath('C:\Users\twest\Documents\Work\MATLAB ADDONS\Neurospec\neurospec21')
end